name: foxy
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^10.2.0
  get_it: ^9.0.5
  laconic: ^1.0.2
  logger: ^2.4.0
  lucide_icons_flutter: ^3.1.6
  mysql_client: ^0.0.27
  package_info_plus: ^9.0.0
  path: ^1.9.1
  shadcn_ui: ^0.43.0
  signals: ^6.0.2
  signals_flutter: ^6.0.2
  url_launcher: ^6.3.1
  window_manager: ^0.5.1
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.2.5
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/image/
